### ISSUE TITLE
Deliter 1.1.2 deleted all of my TNH characters

### ISSUE THREAD

**Issue by O-Deka-K** [H3VR-Modding/Deliter#8]
I'm running the Alpha build of H3VR.

Today, I updated to Deliter 1.1.2. When I launched the game, all of my TNH characters were gone. Only the vanilla characters appeared.

I figured out that it deleted the .deli file from every TNH character in my profile. As far as I know, TNHTweaker doesn't work without the .deli file.

I had to revert to Deliter version 1.1.1 and reinstall all of my characters (I suppose I could have renamed all of the .deli.bak files back instead). After that, it works fine again.

**Comment by nrgill28** [comment]
Should be fixed with 1.1.3, thanks for the report.
